swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /:
        get:
            tags:
                - todo
            summary: list todo
            description: List all todo items
            operationId: todo#list
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/Todo'
            schemes:
                - http
        post:
            tags:
                - todo
            summary: create todo
            description: Create a new todo item
            operationId: todo#create
            parameters:
                - name: object
                  in: body
                  required: true
                  schema:
                    type: object
                    properties:
                        title:
                            type: string
                            description: Title of the todo
                            example: Cupiditate eaque nihil dolore corrupti odit.
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/Todo'
                        required:
                            - id
                            - title
                            - completed
            schemes:
                - http
definitions:
    Todo:
        title: Todo
        type: object
        properties:
            completed:
                type: boolean
                description: Whether the todo is completed
                example: true
            id:
                type: integer
                description: Unique ID
                example: 1888045106
                format: int32
            title:
                type: string
                description: Title of the todo
                example: Adipisci eos vel.
        description: A single todo item
        example:
            completed: true
            id: 1873937695
            title: Ut voluptatum molestias assumenda ea quia.
        required:
            - id
            - title
            - completed
