openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for todo
paths:
    /:
        get:
            tags:
                - todo
            summary: list todo
            description: List all todo items
            operationId: todo#list
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Todo'
                                example:
                                    - completed: false
                                      id: 1671529136
                                      title: Laboriosam quibusdam.
                                    - completed: false
                                      id: 1671529136
                                      title: Laboriosam quibusdam.
                            example:
                                - completed: false
                                  id: 1671529136
                                  title: Laboriosam quibusdam.
                                - completed: false
                                  id: 1671529136
                                  title: Laboriosam quibusdam.
        post:
            tags:
                - todo
            summary: create todo
            description: Create a new todo item
            operationId: todo#create
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            title: "0"
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Todo'
                            example:
                                completed: false
                                id: 1827583355
                                title: Dolor totam aut iusto repudiandae.
components:
    schemas:
        CreateRequestBody:
            type: object
            properties:
                title:
                    type: string
                    description: Title of the todo
                    example: z6
                    minLength: 1
            example:
                title: "1"
            required:
                - title
        Todo:
            type: object
            properties:
                completed:
                    type: boolean
                    description: Whether the todo is completed
                    example: false
                id:
                    type: integer
                    description: Unique ID
                    example: 2049882206
                    format: int32
                title:
                    type: string
                    description: Title of the todo
                    example: Quasi facere.
            description: A single todo item
            example:
                completed: false
                id: 395025621
                title: Accusantium ut quis voluptatem vel libero.
            required:
                - id
                - title
                - completed
tags:
    - name: todo
      description: The todo service manages todo items
